[build-system]
requires = ["setuptools>=42","wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 105

[tool.isort]
profile = "black"
line_length = 105

[tool.coverage.paths]
source = [
    "src",
    "*/site-packages"
]

[tool.mypy]
plugins = "numpy.typing.mypy_plugin"