white_en_passant_sans = ["e4", "a6", "e5", "d5"]
black_en_passant_sans = ["a3", "e5", "a4", "e4", "d4"]

white_no_queenside_sans = ["a3", "e5", "Ra2", "d5", "Ra1", "f5"]
white_no_kingside_sans = ["Nf3", "e5", "Rg1", "d5", "Rh1", "f5", "Ng1"]
white_no_castling_sans = ["e4", "e5", "Ke2", "d5", "Ke1", "f5"]
black_no_queenside_sans = ["e4", "a6", "e5", "Ra7", "Bc4", "Ra8", "Bd3"]
black_no_kingside_sans = ["e4", "h6", "e5", "Rh7", "Bc4", "Rh8", "Bd3"]
black_no_castling_sans = ["e4", "e5", "Bc4", "Ke7", "Nf3", "Ke8"]

white_castled_black_not_yet_sans = ["e4", "e5", "Bc4", "Bc5", "Nf3", "Ne7", "O-O", "f6", "Ng5", "a6"]

scholars_mate_sans = ["e4", "e5", "Qh5", "Nc6", "Bc4", "Nf6", "Qxf7#"]
alpha_zeros_immortal_zugzwang_sans = [
    "Nf3",
    "Nf6",
    "c4",
    "b6",
    "d4",
    "e6",
    "g3",
    "Ba6",
    "Qc2",
    "c5",
    "d5",
    "exd5",
    "cxd5",
    "Bb7",
    "Bg2",
    "Nxd5",
    "O-O",
    "Nc6",
    "Rd1",
    "Be7",
    "Qf5",
    "Nf6",
    "e4",
    "g6",
    "Qf4",
    "O-O",
    "e5",
    "Nh5",
    "Qg4",
    "Re8",
    "Nc3",
    "Qb8",
    "Nd5",
    "Bf8",
    "Bf4",
    "Qc8",
    "h3",
    "Ne7",
    "Ne3",
    "Bc6",
    "Rd6",
    "Ng7",
    "Rf6",
    "Qb7",
    "Bh6",
    "Nd5",
    "Nxd5",
    "Bxd5",
    "Rd1",
    "Ne6",
    "Bxf8",
    "Rxf8",
    "Qh4",
    "Bc6",
    "Qh6",
    "Rae8",
    "Rd6",
    "Bxf3",
    "Bxf3",
    "Qa6",
    "h4",
    "Qa5",
    "Rd1",
    "c4",
    "Rd5",
    "Qe1+",
    "Kg2",
    "c3",
    "bxc3",
    "Qxc3",
    "h5",
    "Re7",
    "Bd1",
    "Qe1",
    "Bb3",
    "Rd8",
    "Rf3",
    "Qe4",
    "Qd2",
    "Qg4",
    "Bd1",
    "Qe4",
    "h6",
    "Nc7",
    "Rd6",
    "Ne6",
    "Bb3",
    "Qxe5",
    "Rd5",
    "Qh8",
    "Qb4",
    "Nc5",
    "Rxc5",
    "bxc5",
    "Qh4",
    "Rde8",
    "Rf6",
    "Rf8",
    "Qf4",
    "a5",
    "g4",
    "d5",
    "Bxd5",
    "Rd7",
    "Bc4",
    "a4",
    "g5",
    "a3",
    "Qf3",
    "Rc7",
    "Qxa3",
    "Qxf6",
    "gxf6",
    "Rfc8",
    "Qd3",
    "Rf8",
    "Qd6",
    "Rfc8",
    "a4",
]
